export default {
  id: "bm",
  name: "Bokmålsordboka",
  concepts: {
    adj: { class: "grammar", expansion: "adjektiv" },
    adjsk: { class: "grammar", expansion: "adjektivisk" },
    adv: { class: "grammar", expansion: "adverb" },
    akk: { class: "grammar", expansion: "akkusativ" },
    am: { class: "language", expansion: "amerikansk" },
    "am-eng": { class: "language", expansion: "amerikansk-engelsk" },
    am_e: { class: "language", expansion: "amerikanske" },
    ags: { class: "language", expansion: "angelsaksisk" },
    arab: { class: "language", expansion: "arabisk" },
    arkais: { class: "rhetoric", expansion: "arkaiserende" },
    art: { class: "relation", expansion: "artikkel" },
    art_en: { class: "relation", expansion: "artikkelen" },
    astron: { class: "domain", expansion: "astronomi" },
    avl: { class: "relation", expansion: "avledning" },
    besl: { class: "relation", expansion: "beslektet" },
    b: { class: "grammar", expansion: "bestemt" },
    bet: { class: "relation", expansion: "betydning" },
    bet_er: { class: "relation", expansion: "betydninger" },
    bibl: { class: "domain", expansion: "bibelspråk" },
    bil: { class: "rhetoric", expansion: "bildelig" },
    bio: { class: "domain", expansion: "biologi" },
    bl_a: { class: null, expansion: "blant annet" },
    bm: { class: "language", expansion: "bokmål" },
    bot: { class: "domain", expansion: "botanikk" },
    d_e: { class: null, expansion: "d e" },
    d_s: { class: null, expansion: "d s" },
    da: { class: "language", expansion: "dansk" },
    da_e: { class: "language", expansion: "danske" },
    dat: { class: "grammar", expansion: "dativ" },
    dim: { class: "grammar", expansion: "diminutiv" },
    "dim-suff": { class: "grammar", expansion: "diminutivssuffiks" },
    dvs: { class: null, expansion: "dvs." },
    eKr: { class: "temporal", expansion: "e.Kr." },
    eg: { class: null, expansion: "egentlig" },
    egl: { class: null, expansion: "egentlig" },
    eigl: { class: null, expansion: "eigl" },
    e: { class: "temporal", expansion: "eldre" },
    eldre: { class: "temporal", expansion: "eldre" },
    el: { class: "relation", expansion: "eller" },
    e_l: { class: null, expansion: "eller lignende" },
    eng: { class: "language", expansion: "engelsk" },
    eng_e: { class: "language", expansion: "engelske" },
    ent: { class: "grammar", expansion: "entall" },
    eint: { class: "grammar", expansion: "eint" },
    ev: { class: null, expansion: "eventuelt" },
    fKr: { class: "temporal", expansion: "f.Kr." },
    fag: { class: "domain", expansion: "fagspråk" },
    fellesgerm: { class: "language", expansion: "fellesgermansk" },
    f: { class: "grammar", expansion: "femininum" },
    filos: { class: "domain", expansion: "filosofi" },
    flat: { class: null, expansion: "flat" },
    fl: { class: "grammar", expansion: "flertall" },
    fls: { class: "grammar", expansion: "flertalls" },
    f_eks: { class: null, expansion: "for eksempel" },
    t_d: { class: null, expansion: "t_d" },
    forb: { class: "relation", expansion: "forbindelse" },
    forb_r: { class: "relation", expansion: "forbindelser" },
    foreld: { class: "temporal", expansion: "foreldet" },
    forh: { class: null, expansion: "forhold" },
    fork_a: { class: null, expansion: "forkorta" },
    fork: { class: null, expansion: "forkorting" },
    fork_ing: { class: null, expansion: "forkorting" },
    forst: { class: "grammar", expansion: "forsterkende" },
    fr: { class: "language", expansion: "fransk" },
    "fr-lat": { class: "language", expansion: "fransk-latin" },
    fr_e: { class: "language", expansion: "franske" },
    fris: { class: "language", expansion: "frisisk" },
    faer: { class: "language", expansion: "færøysk" },
    g: { class: null, expansion: "g" },
    gram: { class: null, expansion: "g" },
    gl: { class: "temporal", expansion: "gammel" },
    gda: { class: "language", expansion: "gammeldansk" },
    geng: { class: "language", expansion: "gammelengelsk" },
    gfr: { class: "language", expansion: "gammelfransk" },
    gfris: { class: "language", expansion: "gammelfrisisk" },
    ggerm: { class: "language", expansion: "gammelgermansk" },
    ghty: { class: "language", expansion: "gammelhøytysk" },
    git: { class: "language", expansion: "gammelitaliensk" },
    glat: { class: "language", expansion: "gammellatin" },
    glty: { class: "language", expansion: "gammellavtysk" },
    gnederl: { class: "language", expansion: "gammelnederlandsk" },
    gno: { class: "language", expansion: "gammelnorsk" },
    gruss: { class: "language", expansion: "gammelrussisk" },
    gsaks: { class: "language", expansion: "gammelsaksisk" },
    gslav: { class: "language", expansion: "gammelslavisk" },
    gsv: { class: "language", expansion: "gammelsvensk" },
    glt: { class: "temporal", expansion: "gammelt" },
    gty: { class: "language", expansion: "gammeltysk" },
    gen: { class: "grammar", expansion: "genitiv" },
    germ: { class: "language", expansion: "germansk" },
    gj: { class: "relation", expansion: "gjennom" },
    got: { class: "language", expansion: "gotisk" },
    gramm: { class: "grammar", expansion: "grammatikk" },
    gr: { class: "language", expansion: "gresk" },
    "gr-lat": { class: "language", expansion: "gresk-latin" },
    gr_e: { class: "language", expansion: "greske" },
    hebr: { class: "language", expansion: "hebraisk" },
    hty: { class: "language", expansion: "høytysk" },
    i_anat: { class: "domain", expansion: "i anatomi" },
    i_astron: { class: "domain", expansion: "i astronomi" },
    i_bibl: { class: "domain", expansion: "i bibelspråk" },
    i_biokjm: { class: "domain", expansion: "i biokjemi" },
    i_biol: { class: "domain", expansion: "i biologi" },
    i_bot: { class: "domain", expansion: "i botanikk" },
    i_dial: { class: "domain", expansion: "i dialekt" },
    dial: { class: "domain", expansion: "i dialekter" },
    i_fag: { class: "domain", expansion: "i fagspråk" },
    i_filos: { class: "domain", expansion: "i filosofi" },
    i_forb_m: { class: "relation", expansion: "i forbindelse med" },
    i_forb: { class: "relation", expansion: "i forbindelsen" },
    fys: { class: "domain", expansion: "i fysikk" },
    i_fys: { class: "domain", expansion: "i fysikk" },
    i_fysiol: { class: "domain", expansion: "i fysiologi" },
    i_geol: { class: "domain", expansion: "i geologi" },
    i_gram: { class: "domain", expansion: "i grammatikk" },
    i_gramm: { class: "domain", expansion: "i grammatikk" },
    i_gr_myt: { class: "domain", expansion: "i gresk mytologi" },
    i_idr: { class: "domain", expansion: "i idrett" },
    i_jus: { class: "domain", expansion: "i jus" },
    i_kjem: { class: "domain", expansion: "i kjemi" },
    i_mat: { class: "domain", expansion: "i matematikk" },
    i_med: { class: "domain", expansion: "i medisin" },
    i_mil: { class: "domain", expansion: "i militærspråk" },
    i_mus: { class: "domain", expansion: "i musikk" },
    i_myt: { class: "domain", expansion: "i mytologi" },
    i_norr_myt: { class: "domain", expansion: "i norrøn mytologi" },
    overf: { class: "rhetoric", expansion: "i overført betydning" },
    i_pol: { class: "domain", expansion: "i politikk" },
    pol: { class: "domain", expansion: "i politikk" },
    i_psyk: { class: "domain", expansion: "i psykologi" },
    i_rel: { class: "domain", expansion: "i religiøst språk" },
    i_spraakv: { class: "domain", expansion: "i språkvitenskap" },
    i_tekn_s: { class: "domain", expansion: "i teknisk språk" },
    i_teol: { class: "domain", expansion: "i teologi" },
    i_typ: { class: "domain", expansion: "i typografi" },
    i_zool: { class: "domain", expansion: "i zoologi" },
    i_oekol: { class: "domain", expansion: "i økologi" },
    idr: { class: "domain", expansion: "idrett" },
    imp: { class: "grammar", expansion: "imperativ" },
    ieur: { class: "language", expansion: "indoeuropeisk" },
    inf: { class: "grammar", expansion: "infinitiv" },
    innv: { class: null, expansion: "innvirkning" },
    inv: { class: null, expansion: "innvirkning" },
    interj: { class: "grammar", expansion: "interjeksjon" },
    intr: { class: "grammar", expansion: "intransitivt" },
    iron: { class: "rhetoric", expansion: "ironisk" },
    isl: { class: "language", expansion: "islandsk" },
    it: { class: "language", expansion: "italiensk" },
    el_l: { class: null, expansion: "eller lignende" },
    it_e: { class: "language", expansion: "italienske" },
    jf: { class: "relation", expansion: "jamfør" },
    jpn: { class: "language", expansion: "japansk" },
    jur: { class: "domain", expansion: "jus" },
    jy: { class: "language", expansion: "jysk" },
    kat: { class: "domain", expansion: "katolsk" },
    kat_e: { class: "domain", expansion: "katolske" },
    kelt: { class: "language", expansion: "keltisk" },
    kg: { class: null, expansion: "kilogram" },
    kjem: { class: "domain", expansion: "kjemisk" },
    kl: { class: null, expansion: "kl." },
    kol: { class: null, expansion: "kollektivt" },
    koll: { class: null, expansion: "kollektivt" },
    komp: { class: "grammar", expansion: "komparativ" },
    konj: { class: "grammar", expansion: "konjunksjon" },
    lat: { class: "language", expansion: "latin" },
    latsk: { class: "language", expansion: "latsk" },
    lty: { class: "language", expansion: "lavtysk" },
    litt: { class: "rhetoric", expansion: "litterært språk" },
    m: { class: null, expansion: "m" },
    m_oms_t: { class: "relation", expansion: "m oms t" },
    mask: { class: "grammar", expansion: "maskulinum" },
    mat: { class: "domain", expansion: "matematikk" },
    med: { class: "domain", expansion: "medisin" },
    meds: { class: "domain", expansion: "medisinsk" },
    mno: { class: "language", expansion: "mellomnorsk" },
    mlat: { class: "language", expansion: "middelalderlatin" },
    mda: { class: "language", expansion: "middeldansk" },
    meng: { class: "language", expansion: "middelengelsk" },
    mhty: { class: "language", expansion: "middelhøytysk" },
    msv: { class: "language", expansion: "middelsvensk" },
    mty: { class: "language", expansion: "middeltysk" },
    mil: { class: "domain", expansion: "militærstell" },
    mots: { class: "relation", expansion: "motsatt" },
    mus: { class: "domain", expansion: "musikk" },
    myt: { class: "domain", expansion: "mytologi" },
    malf: { class: "language", expansion: "målføre" },
    nederl: { class: "language", expansion: "nederlandsk" },
    neds: { class: "rhetoric", expansion: "nedsettende" },
    nom: { class: "grammar", expansion: "nominativ" },
    nordam: { class: "language", expansion: "nordamerikansk" },
    nord: { class: "language", expansion: "nordisk" },
    norr_n: { class: "language", expansion: "norrøn" },
    norr_e: { class: "language", expansion: "norrøne" },
    norr: { class: "language", expansion: "norrønt" },
    no: { class: "language", expansion: "norsk" },
    "no-da": { class: "language", expansion: "norsk-dansk" },
    no_e: { class: "language", expansion: "norske" },
    nr: { class: null, expansion: "nummer" },
    nyd: { class: null, expansion: "nydanning" },
    nda: { class: "language", expansion: "nydansk" },
    ngr: { class: "language", expansion: "nygresk" },
    nygr: { class: "language", expansion: "nygresk" },
    nisl: { class: "language", expansion: "nyislandsk" },
    nyl: { class: null, expansion: "nylaging" },
    nlat: { class: "language", expansion: "nylatin" },
    nyno: { class: "language", expansion: "nynorsk" },
    n: { class: "grammar", expansion: "nøytrum" },
    "obj-": { class: "grammar", expansion: "objekts" },
    off: { class: null, expansion: "offentlig" },
    o_ae: { class: null, expansion: "og andre" },
    o_a: { class: null, expansion: "og annet" },
    o_l: { class: null, expansion: "og lignende" },
    o_norr_forh: { class: "domain", expansion: "om norrøne forhold" },
    opph: { class: "relation", expansion: "opphav" },
    opphl: { class: "relation", expansion: "opphavlig" },
    osv: { class: null, expansion: "osv." },
    pt: { class: "grammar", expansion: "partisipp" },
    pass: { class: "grammar", expansion: "passiv" },
    pf: { class: "grammar", expansion: "perfektum" },
    pf_pt: { class: "grammar", expansion: "perfektum partisipp" },
    pers: { class: null, expansion: "person" },
    poet_s: { class: "rhetoric", expansion: "poetisk språk" },
    port: { class: "language", expansion: "portugisisk" },
    pref: { class: "grammar", expansion: "prefiks" },
    prep: { class: "grammar", expansion: "preposisjon" },
    pr: { class: "grammar", expansion: "presens" },
    pres: { class: "grammar", expansion: "presens" },
    pr_pt: { class: "grammar", expansion: "presens partisipp" },
    pret: { class: "grammar", expansion: "preteritum" },
    pron: { class: "grammar", expansion: "pronomen" },
    pga: { class: null, expansion: "på grunn av" },
    refl: { class: "grammar", expansion: "refleksivt" },
    rel: { class: "domain", expansion: "religiøse" },
    rom: { class: "language", expansion: "romansk" },
    russ: { class: "language", expansion: "russisk" },
    russ_e: { class: "language", expansion: "russiske" },
    s_d: { class: null, expansion: "s d" },
    saks: { class: "language", expansion: "saksisk" },
    sam: { class: "language", expansion: "samisk" },
    sm: { class: "relation", expansion: "samme" },
    sm_o: { class: "relation", expansion: "samme opphav" },
    sm_o_s: { class: "relation", expansion: "samme opprinnelse som" },
    smbl: { class: "relation", expansion: "sammenblanding" },
    smh: { class: "relation", expansion: "sammenheng" },
    sms: { class: "relation", expansion: "sammensetning" },
    sms_er: { class: "relation", expansion: "sammensetninger" },
    sengr: { class: "language", expansion: "sengresk" },
    seinlat: { class: "language", expansion: "senlatin" },
    senlat: { class: "language", expansion: "senlatin" },
    shet: { class: "language", expansion: "shetlandsk" },
    sj: { class: null, expansion: "sjelden" },
    skjemt: { class: "rhetoric", expansion: "skjemtende" },
    slav: { class: "language", expansion: "slavisk" },
    sm_st: { class: null, expansion: "sm st" },
    s_adj: { class: "grammar", expansion: "som adjektiv" },
    s_adv: { class: "grammar", expansion: "som adverb" },
    s_subst: { class: "grammar", expansion: "som substantiv" },
    sp: { class: "language", expansion: "spansk" },
    "sp-am": { class: "language", expansion: "spansk-amerikansk" },
    spraakv: { class: "domain", expansion: "språkvitenskap" },
    spoekt: { class: "rhetoric", expansion: "spøkefullt" },
    subj: { class: "grammar", expansion: "subjekt" },
    subst: { class: "grammar", expansion: "substantiv" },
    subst_t: { class: "grammar", expansion: "substantivert" },
    subst_isk: { class: "grammar", expansion: "substantivisk" },
    suff: { class: "grammar", expansion: "suffiks" },
    superl: { class: "grammar", expansion: "superlativ" },
    "svar._t": { class: "relation", expansion: "svar. t" },
    sv: { class: "language", expansion: "svensk" },
    sv_e: { class: "language", expansion: "svenske" },
    saerl: { class: null, expansion: "særlig" },
    soeram: { class: "language", expansion: "søramerikansk" },
    soerfr: { class: "language", expansion: "sørfransk" },
    tidl: { class: "temporal", expansion: "tidligere" },
    t_forsk_f: { class: "relation", expansion: "til forskjell fra" },
    t_forskj_fra: { class: "relation", expansion: "til forskjell fra" },
    t_skiln: { class: "relation", expansion: "t_skiln" },
    tr: { class: "grammar", expansion: "transitivt" },
    trol: { class: null, expansion: "trolig" },
    tsjekk: { class: "language", expansion: "tsjekkisk" },
    tyd: { class: null, expansion: "tyding" },
    tyrk: { class: "language", expansion: "tyrkisk" },
    ty: { class: "language", expansion: "tysk" },
    ty_e: { class: "language", expansion: "tyske" },
    ub: { class: "grammar", expansion: "ubestemt" },
    ubf: { class: "grammar", expansion: "ubestemt form" },
    uboey: { class: "grammar", expansion: "ubøyelig" },
    upers: { class: "grammar", expansion: "upersonlig" },
    uspes: { class: null, expansion: "uspesifisert" },
    utenl: { class: null, expansion: "utenlandske" },
    utt: { class: null, expansion: "uttale" },
    utr: { class: null, expansion: "uttrykk" },
    uttr: { class: null, expansion: "uttrykk" },
    uttr_et: { class: null, expansion: "uttrykket" },
    uttr_t: { class: null, expansion: "uttrykket" },
    vha: { class: null, expansion: "ved hjelp av" },
    vsa: { class: null, expansion: "ved siden av" },
    v: { class: "grammar", expansion: "verb" },
    verb: { class: "grammar", expansion: "verb" },
    p_g_a: { class: null, expansion: "på grunn av" },
    vbs: { class: "grammar", expansion: "verbalsubstantiv" },
    y_st: { class: null, expansion: "y st" },
    zool: { class: "domain", expansion: "zoologi" },
    subs_isk: { class: "grammar", expansion: "subs_isk" },
    utanl: { class: null, expansion: "utanl" },
    "am.-eng.": { class: "language", expansion: "amerikansk" },
    "arab.": { class: "language", expansion: "arabisk" },
    "da.": { class: "language", expansion: "dansk" },
    "eng.": { class: "language", expansion: "engelsk" },
    "fr.": { class: "language", expansion: "fransk" },
    "fris.": { class: "language", expansion: "frisisk" },
    "fær.": { class: "language", expansion: "færøysk" },
    "g.da.": { class: "language", expansion: "gammeldansk" },
    "g.eng.": { class: "language", expansion: "gammelengelsk" },
    "germ.": { class: "language", expansion: "germansk" },
    "g.fr.": { class: "language", expansion: "gammelfransk" },
    "g.h.ty.": { class: "language", expansion: "gammelhøytysk" },
    "g.lat.": { class: "language", expansion: "gammellatin" },
    "g.l.ty.": { class: "language", expansion: "gammellavtysk" },
    "g.no.": { class: "language", expansion: "gammelnorsk" },
    "got.": { class: "language", expansion: "gotisk" },
    "gr.": { class: "language", expansion: "gresk" },
    "g.russ.": { class: "language", expansion: "gammelrussisk" },
    "g.sv.": { class: "language", expansion: "gammelsvensk" },
    "g.ty.": { class: "language", expansion: "gammeltysk" },
    "hebr.": { class: "language", expansion: "hebraisk" },
    "h.ty.": { class: "language", expansion: "høytysk" },
    "i.eur.": { class: "language", expansion: "indoeuropeisk" },
    "isl.": { class: "language", expansion: "islandsk" },
    "it.": { class: "language", expansion: "italiensk" },
    "jy.": { class: "language", expansion: "jysk" },
    "kelt.": { class: "language", expansion: "keltisk" },
    "lat.": { class: "language", expansion: "latin" },
    "l.ty.": { class: "language", expansion: "lavtysk" },
    "m.eng.": { class: "language", expansion: "middelengelsk" },
    "m.h.ty.": { class: "language", expansion: "middelhøytysk" },
    "m.lat.": { class: "language", expansion: "middelalderlatin" },
    "m.no.": { class: "language", expansion: "mellomnorsk" },
    "m.ty.": { class: "language", expansion: "middeltysk" },
    "nyda.": { class: "language", expansion: "nydansk" },
    "nederl.": { class: "language", expansion: "nederlandsk" },
    finsk: { class: "language", expansion: "finsk" },
    "no.": { class: "language", expansion: "norsk" },
    "no.-da.": { class: "language", expansion: "norsk-dansk" },
    "nord.": { class: "language", expansion: "nordisk" },
    "bm.": { class: "language", expansion: "bokmål" },
    "nordam.": { class: "language", expansion: "nordamerikansk" },
    "norr.": { class: "language", expansion: "norrønt" },
    "nyno.": { class: "language", expansion: "nynorsk" },
    "port.": { class: "language", expansion: "portugisisk" },
    "rom.": { class: "language", expansion: "romansk" },
    "russ.": { class: "language", expansion: "russisk" },
    "saks.": { class: "language", expansion: "saksisk" },
    "sam.": { class: "language", expansion: "samisk" },
    "senlat.": { class: "language", expansion: "senlatin" },
    "shet.": { class: "language", expansion: "shetlandsk" },
    "slav.": { class: "language", expansion: "slavisk" },
    "sp.": { class: "language", expansion: "spansk" },
    "sv.": { class: "language", expansion: "svensk" },
    "sør-am.": { class: "language", expansion: "søramerikansk" },
    "tsjekk.": { class: "language", expansion: "tsjekkisk" },
    "ty.": { class: "language", expansion: "tysk" },
    algonkin: { class: "language", expansion: "algonkin" },
    tyrkisk: { class: "language", expansion: "tyrkisk" },
    malayisk: { class: "language", expansion: "malayisk" },
    sørkinesisk: { class: "language", expansion: "sørkinesisk" },
    marathi: { class: "language", expansion: "marathi" },
    hindi: { class: "language", expansion: "hindi" },
    sanskrit: { class: "language", expansion: "sanskrit" },
    polsk: { class: "language", expansion: "polsk" },
    persisk: { class: "language", expansion: "persisk" },
    ungarsk: { class: "language", expansion: "ungarsk" },
    semittisk: { class: "language", expansion: "semittisk" },
    egyptisk: { class: "language", expansion: "egyptisk" },
    bretonsk: { class: "language", expansion: "bretonsk" },
    singalesisk: { class: "language", expansion: "singalesisk" },
    "g.fris.": { class: "language", expansion: "gammelfrisisk" },
    provençalsk: { class: "language", expansion: "provençalsk" },
    japansk: { class: "language", expansion: "japansk" },
    aleutisk: { class: "language", expansion: "aleutisk" },
    malayalam: { class: "language", expansion: "malayalam" },
    turkotatarisk: { class: "language", expansion: "turkotatarisk" },
    nepali: { class: "language", expansion: "nepali" },
    jakutisk: { class: "language", expansion: "jakutisk" },
    hawaiisk: { class: "language", expansion: "hawaiisk" },
    "g.slav.": { class: "language", expansion: "gammelslavisk" },
    tamil: { class: "language", expansion: "tamil" },
    senegalesisk: { class: "language", expansion: "senegalesisk" },
    urdu: { class: "language", expansion: "urdu" },
    gælisk: { class: "language", expansion: "gælisk" },
    indianerspråk: { class: "language", expansion: "indianerspråk" },
    quechua: { class: "language", expansion: "quechua" },
    bengali: { class: "language", expansion: "bengali" },
    "karibisk språk": { class: "language", expansion: "karibisk språk" },
    "australsk språk": { class: "language", expansion: "australsk språk" },
    "tupi-språket": { class: "language", expansion: "tupi-språket" },
    bantuspråk: { class: "language", expansion: "bantuspråk" },
    "indisk språk": { class: "language", expansion: "indisk språk" },
    "afrikansk språk": { class: "language", expansion: "afrikansk språk" },
    romani: { class: "language", expansion: "romani" },
    romanes: { class: "language", expansion: "romanes" },
    "ags.": { class: "language", expansion: "angelsaksisk" },
    "m.sv.": { class: "language", expansion: "mellomsvensk" },
    "aram.": { class: "language", expansion: "arameisk" },
    "nylat.": { class: "language", expansion: "nylatin" },
    navnet: { class: "language", expansion: "navnet" },
    varemerke: { class: "language", expansion: "varemerke" },
    guarani: { class: "language", expansion: "guarani" },
    khoikhoi: { class: "language", expansion: "khoikhoi" },
    kinesisk: { class: "language", expansion: "(primært han-)kinesisk" },
    eskimoisk: {
      class: "language",
      expansion: "eskimoisk-aleutiske språk, inkludert grønlandsk",
    },
    "am.-sp-": { class: "language", expansion: "am.-sp-" },
    afrikaans: { class: "language", expansion: "afrikaans" },
    gullah: { class: "language", expansion: "gullah" },
    wolof: { class: "language", expansion: "wolof" },
    lydord: { class: "language", expansion: "lydord" },
    nigerkongo: { class: "language", expansion: "nigerkongo" },
    bf: { class: "grammar", expansion: "bestemt form" },
    m_a: { class: null, expansion: "mellom annet" },
    m_m: { class: null, expansion: "med mer" },
    tupi: { class: "language", expansion: "tupí-guaraní" },
    oppr: { class: null, expansion: "opprinnelig" },
    amp: { class: "entity", expansion: "&" },
  },
};
